export type JsonSignalNode = {
  kind: 'signal';
  id: string;
  initial: unknown;
  flags?: {
    in?: boolean;
    out?: boolean;
  };
};

export type JsonComputedNode = {
  kind: 'computed';
  id: string;
  deps: readonly string[];
  logicKey: string;
  flags?: {
    out?: boolean;
  };
};

export type JsonProcessorNode = {
  kind: 'processor';
  id: string;
  deps: readonly string[];
  outputs: readonly string[];
  logicKey: string;
};

export type JsonAsyncNode = {
  kind: 'async';
  id: string;
  deps: readonly string[];
  initial: unknown;
  logicKey: string;
  flags?: {
    out?: boolean;
  };
};

export type JsonConsumerNode = {
  kind: 'consumer';
  id: string;
  deps: readonly string[];
  logicKey: string;
};

export type JsonGraphNode =
  | JsonSignalNode
  | JsonComputedNode
  | JsonProcessorNode
  | JsonAsyncNode
  | JsonConsumerNode;

export type JsonGraphSpecV1 = {
  version: 1;
  nodes: readonly JsonGraphNode[];
};

function isValidIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

function quoteKey(name: string): string {
  const escaped = name.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `'${escaped}'`;
}

function sanitizeIdentifier(name: string): string {
  const normalized = name.replace(/[^A-Za-z0-9_$]+/g, '_').replace(/^(\d)/, '_$1');
  return isValidIdentifier(normalized) ? normalized : `_${normalized}`;
}

export function inferTsTypeFromJsonValue(value: unknown): string {
  if (value === null) {
    return 'null';
  }

  switch (typeof value) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'object':
      return Array.isArray(value) ? 'unknown[]' : 'Record<string, unknown>';
    default:
      return 'unknown';
  }
}

export function generateGraphModel(spec: JsonGraphSpecV1): string {
  const entries = new Map<string, string>();

  const setIfMissing = (id: string, type: string): void => {
    if (!entries.has(id)) {
      entries.set(id, type);
    }
  };

  for (const node of spec.nodes) {
    if (node.kind === 'signal') {
      setIfMissing(node.id, inferTsTypeFromJsonValue(node.initial));
      continue;
    }

    if (node.kind === 'async') {
      setIfMissing(node.id, 'unknown');
      setIfMissing(`${node.id}/result`, inferTsTypeFromJsonValue(node.initial));
      setIfMissing(`${node.id}/loading`, 'boolean');
      setIfMissing(`${node.id}/error`, 'string | null');
      continue;
    }

    // Computed/processor/consumer do not carry value type info in JsonGraphSpecV1.
    setIfMissing(node.id, 'unknown');
  }

  const ids = Array.from(entries.keys()).sort();

  const lines: string[] = [];
  lines.push('// Auto-generated by graph-codegen. DO NOT EDIT.');
  lines.push('');
  lines.push('export interface GraphModel {');

  for (const id of ids) {
    const key = isValidIdentifier(id) ? id : quoteKey(id);
    lines.push(`  ${key}: ${entries.get(id)};`);
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

type IdentityEntry = {
  id: string;
  access: string;
};

export function generateGraphIdentitySurface(
  spec: JsonGraphSpecV1,
  options: { moduleId?: string; exportName?: string } = {},
): string {
  const moduleId = options.moduleId ?? 'generatedGraph';
  const exportName = options.exportName ?? 'GraphIdentity';

  const inputLines: string[] = [];
  const stateLines: string[] = [];
  const outputLines: string[] = [];
  const internalLines: string[] = [];
  const nodeEntries: IdentityEntry[] = [];
  const inputAliases: IdentityEntry[] = [];
  const outputAliases: IdentityEntry[] = [];

  const inputNames = new Set<string>();
  const stateNames = new Set<string>();
  const outputNames = new Set<string>();
  const internalNames = new Set<string>();

  const nextName = (base: string, used: Set<string>): string => {
    let name = sanitizeIdentifier(base);
    if (!used.has(name)) {
      used.add(name);
      return name;
    }
    let index = 2;
    while (used.has(`${name}_${index}`)) {
      index += 1;
    }
    const unique = `${name}_${index}`;
    used.add(unique);
    return unique;
  };

  const addInput = (id: string, type: string): string => {
    const prop = nextName(id, inputNames);
    inputLines.push(`    ${prop}: input<${type}>(),`);
    return `GraphModule.inputs.${prop}`;
  };

  const addState = (id: string, type: string): string => {
    const prop = nextName(id, stateNames);
    stateLines.push(`    ${prop}: state<${type}>(),`);
    const access = `GraphModule.state.${prop}`;
    nodeEntries.push({ id, access });
    return access;
  };

  const addPublicOutput = (id: string, type: string): string => {
    const prop = nextName(id, outputNames);
    outputLines.push(`    ${prop}: output<${type}>(),`);
    return `GraphModule.outputs.${prop}`;
  };

  const addOutputNode = (id: string, type: string): string => {
    const prop = nextName(id, outputNames);
    outputLines.push(`    ${prop}: output<${type}>(),`);
    const access = `GraphModule.outputs.${prop}`;
    nodeEntries.push({ id, access });
    return access;
  };

  const addInternal = (id: string, type = 'void'): string => {
    const prop = nextName(id, internalNames);
    internalLines.push(`    ${prop}: internal<${type}>(),`);
    const access = `GraphModule.internals.${prop}`;
    nodeEntries.push({ id, access });
    return access;
  };

  for (const node of spec.nodes) {
    if (node.kind === 'signal') {
      const signalType = inferTsTypeFromJsonValue(node.initial);
      addState(node.id, signalType);
      if (node.flags?.in) {
        inputAliases.push({ id: node.id, access: addInput(node.id, signalType) });
      }
      if (node.flags?.out) {
        outputAliases.push({ id: node.id, access: addPublicOutput(node.id, signalType) });
      }
      continue;
    }

    if (node.kind === 'computed') {
      if (node.flags?.out) {
        const access = addOutputNode(node.id, 'unknown');
        outputAliases.push({ id: node.id, access });
        continue;
      }

      addInternal(node.id, 'unknown');
      continue;
    }

    if (node.kind === 'async') {
      addInternal(node.id);
      const addAsyncProjection = node.flags?.out ? addOutputNode : addInternal;
      const resultAccess = addAsyncProjection(`${node.id}/result`, inferTsTypeFromJsonValue(node.initial));
      const loadingAccess = addAsyncProjection(`${node.id}/loading`, 'boolean');
      const errorAccess = addAsyncProjection(`${node.id}/error`, 'string | null');

      if (node.flags?.out) {
        outputAliases.push({
          id: `${node.id}/result`,
          access: resultAccess,
        });
        outputAliases.push({
          id: `${node.id}/loading`,
          access: loadingAccess,
        });
        outputAliases.push({
          id: `${node.id}/error`,
          access: errorAccess,
        });
      }
      continue;
    }

    addInternal(node.id);
  }

  const lines: string[] = [];
  lines.push('// Auto-generated by graph-codegen. DO NOT EDIT.');
  lines.push('');
  lines.push("import { defineGraphModule, input, internal, output, state } from 'depa-data-graph-core';");
  lines.push('');
  lines.push(`export const GraphModule = defineGraphModule('${moduleId}', {`);
  if (inputLines.length > 0) {
    lines.push('  inputs: {');
    lines.push(...inputLines);
    lines.push('  },');
  }
  if (stateLines.length > 0) {
    lines.push('  state: {');
    lines.push(...stateLines);
    lines.push('  },');
  }
  if (outputLines.length > 0) {
    lines.push('  outputs: {');
    lines.push(...outputLines);
    lines.push('  },');
  }
  if (internalLines.length > 0) {
    lines.push('  internals: {');
    lines.push(...internalLines);
    lines.push('  },');
  }
  lines.push('} as const);');
  lines.push('');
  lines.push(`export const ${exportName} = {`);
  lines.push('  module: GraphModule,');
  lines.push('  nodes: {');
  for (const entry of [...nodeEntries].sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`    ${quoteKey(entry.id)}: ${entry.access},`);
  }
  lines.push('  },');
  lines.push('  ports: {');
  lines.push('    inputs: {');
  for (const entry of [...inputAliases].sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`      ${quoteKey(entry.id)}: ${entry.access},`);
  }
  lines.push('    },');
  lines.push('    outputs: {');
  for (const entry of [...outputAliases].sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`      ${quoteKey(entry.id)}: ${entry.access},`);
  }
  lines.push('    },');
  lines.push('  },');
  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}
